# Generated by Django 5.1.6 on 2025-03-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task_Manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='Due_Date',
            field=models.DateTimeField(),
        ),
    ]
